### ISSUE TITLE
status in portfolio, transactions and ether balance

### ISSUE THREAD

**Issue by wasy314** [MyBitFoundation/MyBit-Go.app#141]
After contributing to funding an asset, the following don't automatically update, but remain frozen creating the impression that the purchase never happened: 

1. Portfolio -> total portfolio value & the last funded assed
1. Transactions - last transaction doesn't show
1. ETH balance - doesn't adjust to reflect the latest contribution

The only way to have things up to date is to do a manual page refresh.

**Comment by csmartinsfct** [comment]
Fixed in the current release.
