### ISSUE TITLE
Reference of CivicController in Server index.js

### ISSUE THREAD

**Issue by mul53** [MyBitFoundation/MyBit-Go.app#536]
The import causes an error because there is no `CivicController` under the controllers folder
https://github.com/MyBitFoundation/MyBit-Go.app/blob/fe086b2dc7b2d3fa9f6be6cb2b282790d8c4ba3f/server/index.js#L11

**Comment by cryptnotiq** [comment]
you can delete the line civicController - there is no need to import it anymore.
