### ISSUE TITLE
List Asset Function Broken

### ISSUE THREAD

**Issue by cryptnotiq** [MyBitFoundation/MyBit-Go.app#539]
When you choose List Asset in the Nav Bar and go through the tutorial it then leavers you on a page without any option to proceed to the listing process. this could be caused because civic was removed and not replaced with another button to proceed.

<img width="651" alt="Screen Shot 2020-02-08 at 10 03 46" src="https://user-images.githubusercontent.com/43958441/74082464-88272400-4a5a-11ea-842c-75a01fca3a66.png">

**Comment by tcrowe** [comment]
Thank you @cryptnotiq. I have seen and investigated this issue in my testing and I have not yet come to the solution. I will check your clue about Civic.

**Comment by cryptnotiq2** [comment]
@tcrowe were you able to find the cause of this issue?

**Comment by tcrowe** [comment]
Not yet. I will try again today. =]
