### ISSUE TITLE
Airtable Assets did not Migrate to IPFS

### ISSUE THREAD

**Issue by cryptnotiq** [MyBitFoundation/MyBit-Go.app#540]
I believe prior to the migration asset details the images for the asset and possibly the details/description of it where managed in AWS. On the new iteration on IPFS, the pictures are not displaying. Is that a loading error, bc IPFS can be very delayed, or has that yet to be resolved?

**Comment by tcrowe** [comment]
I'm unsure what is the source of those images but I will find out soon.
